version: '3'

services:
  app:
    build: .
    ports:
      - 4002:${PORT}
    environment:
      - MONGO_URL=${DEV_DATABASE_URL}
     
    networks:
      - mas-hms-network  
networks:
  mas-hms-network:
    external: true      