version: '3'

services:
  app:
    build: .
    ports:
      - 4002:${PORT}
    depends_on:
      - mongo
    environment:
      - MONGO_URL= ${DEV_DATABASE_URL}
  mongo:
    image: mongo:latest    
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db  
volumes:
  mongo-data:      